#DATABASE
MYSQL_USERNAME: root
MYSQL_PASSWORD: admin
MYSQL_HOST: 192.168.1.216
MYSQL_PORT: 5432
MYSQL_DB: spcloud-db


#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: prod

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL ADDRESS>
EMAIL_PASSWORD: <YOUR APP PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}